### ISSUE TITLE
Please join my group

### ISSUE THREAD

**Issue by javascript-programmer** [Explosion-Scratch/Explosion-scratch#3]
Hi There I would like To Ask You
Would You like to join me on a project 
Cuz I have joined the nasa space app challenge
and They said I need a team to be accepted

**Comment by Explosion-Scratch** [comment]
Oof oof oof I am really sorry for the late reply.

**Comment by Explosion-Scratch** [comment]
I'm really busy with [Bijou.js](https://bijou.js.org) right now.
