### ISSUE TITLE
how did you get this snake thing

### ISSUE THREAD

**Issue by Oren-Lindsey** [Explosion-Scratch/Explosion-scratch#8]
![snake thing](https://raw.githubusercontent.com/Explosion-Scratch/Explosion-scratch/a407529eda6cf7c81265dae00a6eab19d1597632/github-contribution-grid-snake.svg)

**Comment by Explosion-Scratch** [comment]
Check out the github action

**Comment by Explosion-Scratch** [comment]
Here's the action:

https://github.com/Explosion-Scratch/Explosion-scratch/blob/1c1d73d5372f0202c00add3235fbab8bf503a471/.github/workflows/snake.yml#L20-L32

It generates the SVG and pushes it to an output branch which then hosted on Github pages
